name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - 'kubernetes/deployment.yaml'
  pull_request:
    branches: [main]
  workflow_run:
    workflows: [CI/CD Pipeline]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: odujrn/securetictactoe
  FULL_IMAGE_NAME: ghcr.io/odujrn/securetictactoe

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm test || echo "No tests found, would add tests in a real project"

  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      image_tag: ${{ steps.set_output.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.FULL_IMAGE_NAME }}
          tags: |
            type=sha,format=long

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set image tag output
        id: set_output
        run: |
          IMAGE_REF="${{ steps.meta.outputs.tags }}"
          DIGEST="${IMAGE_REF#*@}"
          echo "image_tag=${DIGEST}" >> $GITHUB_OUTPUT

  update-k8s:
    name: Create PR to Update Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          clean: true

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config pull.rebase false

      - name: Create Branch for Deployment Update
        run: |
          BRANCH_NAME=update-k8s-$(date +%s)
          git checkout -b $BRANCH_NAME
          git pull origin main

          IMAGE="${{ env.FULL_IMAGE_NAME }}"
          IMAGE_DIGEST="${{ needs.docker.outputs.image_tag }}"

          echo "Using image: ${IMAGE}@sha256:${IMAGE_DIGEST}"

          sed -i "s|image:.*|image: ${IMAGE}@sha256:${IMAGE_DIGEST}|g" kubernetes/deployment.yaml
          
          git add kubernetes/deployment.yaml
          git commit -m "CI: Update image digest in deployment.yaml"
          git push origin $BRANCH_NAME

          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          title: "CI: Update image digest in deployment.yaml"
          body: "This PR updates the Kubernetes deployment manifest with the latest image digest."
          head: ${{ env.branch_name }}
          base: main
          draft: false

  argocd-sync:
    name: ArgoCD Sync (After PR Merge)
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger ArgoCD Sync
        run: |
          echo "🔄 Sync ArgoCD..."
          # Example: Using ArgoCD CLI
          # curl -X POST http://your-argocd-server/api/v1/applications/your-app/sync \
          #      -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}"
          echo "Replace above with actual sync method if needed"

  apply-manifests:
    name: (Optional) Apply K8s Manifest with kubectl
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Decode and set up KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: kubectl apply -f kubernetes/
